# Generated by Django 5.2.9 on 2025-12-02 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summary Cache',
                'verbose_name_plural': 'Summary Cache',
            },
        ),
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sub_search', 'Sub Search'), ('auto-ingest', 'Auto Ingest'), ('auto-random', 'Auto Random')], default='manual', max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=128, null=True)),
                ('limit_value', models.IntegerField(blank=True, null=True)),
                ('unmoderated_only', models.BooleanField(default=False)),
                ('exclude_nsfw', models.BooleanField(default=False)),
                ('min_subscribers', models.IntegerField(default=0)),
                ('activity_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('activity_threshold_utc', models.BigIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('result_count', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('checked_count', models.IntegerField(default=0)),
                ('found_count', models.IntegerField(default=0)),
                ('progress_phase', models.CharField(default='queued', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('notification_email', models.EmailField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='search_quer_source_ab0850_idx'), models.Index(fields=['state', '-started_at'], name='search_quer_state_41852d_idx'), models.Index(fields=['celery_task_id'], name='search_quer_celery__430f48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_name_prefixed', models.CharField(blank=True, max_length=140, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('public_description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('subscribers', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_unmoderated', models.BooleanField(db_index=True, default=False)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('last_activity_utc', models.BigIntegerField(blank=True, null=True)),
                ('mod_count', models.IntegerField(blank=True, null=True)),
                ('last_keyword', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subreddits', to='search.queryrun')),
            ],
            options={
                'ordering': ['-subscribers'],
                'indexes': [models.Index(fields=['is_unmoderated', '-subscribers'], name='search_subr_is_unmo_7c9810_idx'), models.Index(fields=['-updated_at'], name='search_subr_updated_b904db_idx')],
            },
        ),
    ]
