# Generated by Django 5.2.9 on 2025-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_add_notification_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subreddit',
            index=models.Index(fields=['is_nsfw', '-subscribers'], name='search_subr_is_nsfw_a702e0_idx'),
        ),
        migrations.AddIndex(
            model_name='subreddit',
            index=models.Index(fields=['last_seen_run', '-subscribers'], name='search_subr_last_se_76ffa1_idx'),
        ),
    ]
