# Generated by Django 5.2.9 on 2025-12-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_discovered_24h', models.IntegerField(default=0)),
                ('subs_updated_24h', models.IntegerField(default=0)),
                ('human_searches_24h', models.IntegerField(default=0)),
                ('bot_searches_24h', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rolling Stats',
                'verbose_name_plural': 'Rolling Stats',
            },
        ),
    ]
