# Generated by Django 5.2.9 on 2025-12-04 01:56

import django.utils.timezone
from django.db import migrations, models


def copy_started_at_to_created_at(apps, schema_editor):
    """Copy started_at values to created_at for existing records."""
    QueryRun = apps.get_model('search', 'QueryRun')
    for run in QueryRun.objects.all():
        if run.started_at:
            run.created_at = run.started_at
            run.save(update_fields=['created_at'])


def reverse_copy(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_add_rollingstats'),
    ]

    operations = [
        # First add the field with a default
        migrations.AddField(
            model_name='queryrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Copy existing started_at values to created_at
        migrations.RunPython(copy_started_at_to_created_at, reverse_copy),
        # Now alter started_at to be nullable
        migrations.AlterField(
            model_name='queryrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Update meta options and indexes
        migrations.AlterModelOptions(
            name='queryrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='queryrun',
            name='search_quer_source_ab0850_idx',
        ),
        migrations.RemoveIndex(
            model_name='queryrun',
            name='search_quer_state_41852d_idx',
        ),
        migrations.AddIndex(
            model_name='queryrun',
            index=models.Index(fields=['source', '-created_at'], name='search_quer_source_104840_idx'),
        ),
        migrations.AddIndex(
            model_name='queryrun',
            index=models.Index(fields=['state', '-created_at'], name='search_quer_state_cf4928_idx'),
        ),
    ]
