# Generated by Django 5.2.9 on 2025-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_add_created_at_to_queryrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrun',
            name='retried_from_job_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
