# Generated by Django 5.2.9 on 2025-12-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_add_retry_tracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryCache',
        ),
    ]
