# Generated by Django 5.2.9 on 2025-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('reddit_username', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('system_details', models.CharField(blank=True, max_length=512, null=True)),
                ('availability', models.CharField(blank=True, max_length=256, null=True)),
                ('bandwidth_notes', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('health_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('broken', 'Broken')], db_index=True, default='pending', max_length=32)),
                ('last_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('broken_since', models.DateTimeField(blank=True, null=True)),
                ('manage_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('manage_token_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['health_status', '-updated_at'], name='nodes_volun_health__c0d9d7_idx')],
            },
        ),
    ]
